// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>

namespace AuthTest.Web
{
    public partial class ChangePasswordPage
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.Button btnChangePassword;
    }
}
