// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>

namespace AuthTest.Web
{
    public partial class Default
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
