// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>

namespace AuthTest.Web
{
    public partial class EnrollPage
    {
        protected global::System.Web.UI.WebControls.Label lblRegisterError;
        protected global::System.Web.UI.WebControls.HiddenField hdnCreationOptions;
        protected global::System.Web.UI.WebControls.HiddenField hdnAttestationResponse;
        protected global::System.Web.UI.WebControls.TextBox txtKeyName;
        protected global::System.Web.UI.WebControls.Button btnRegisterComplete;
        protected global::System.Web.UI.WebControls.Button btnContinue;
        protected global::System.Web.UI.WebControls.Button btnSkip;
        protected global::System.Web.UI.WebControls.Panel pnlRegisterWebAuthn;
        protected global::System.Web.UI.WebControls.Panel pnlComplete;
    }
}
