// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>

namespace AuthTest.Web
{
    public partial class LoginPage
    {
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlUsername;
        protected global::System.Web.UI.WebControls.TextBox txtUsername;
        protected global::System.Web.UI.WebControls.Button btnCheckUsername;
        protected global::System.Web.UI.WebControls.Panel pnlPassword;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.Button btnLogin;
        protected global::System.Web.UI.WebControls.Panel pnlWebAuthn;
        protected global::System.Web.UI.WebControls.HiddenField hdnAssertionOptions;
        protected global::System.Web.UI.WebControls.HiddenField hdnAssertionResponse;
        protected global::System.Web.UI.WebControls.Button btnWebAuthnComplete;
    }
}
