// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>

namespace AuthTest.Web
{
    public partial class UsersPage
    {
        protected global::System.Web.UI.WebControls.Label lblCurrentUser;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.GridView gvUsers;
        protected global::System.Web.UI.WebControls.Button btnLogout;
    }
}
